name: Clean Dataset

on:
  push:
    branches:
      - master  # Replace 'main' with the name of your main branch

jobs:
  clean:
    name: Clean Dataset
    runs-on: ubuntu-latest  # You can choose the runner platform here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9  # Replace '3.x' with your Python version

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Explicitly specify Node.js 16

      - name: Run cleanData
        run: python cleanData.py  # Replace 'path/to/clean.py' with the actual path to your clean.py script

      - name: Commit changes
        run: |
          git config --local user.email "diallomous@github.com"
          git config --local user.name "Moussa DIALLO"
          git add .
          git commit -m "Auto clean dataset after push"
          git push
